basePath: /api/v1
definitions:
  dtos.UserSignUpRequest:
    properties:
      name:
        description: 'required: true'
        type: string
      password:
        description: 'required: true'
        type: string
      phone:
        description: 'required: true'
        type: string
    required:
    - name
    - password
    - phone
    type: object
  dtos.UserSignUpResponse:
    properties:
      token:
        description: 'required: true'
        type: string
    required:
    - token
    type: object
info:
  contact: {}
  description: API Documentation
  title: Auth Service API Doc
  version: "1.0"
paths:
  /signup:
    post:
      consumes:
      - application/json
      description: SignUp a user for the first time
      parameters:
      - description: User SignUp Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UserSignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.UserSignUpResponse'
      summary: SignUp a user
      tags:
      - Auth
swagger: "2.0"
