version: "3"
services:
  mysql_database:
    image: mysql
    container_name: mysql_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3009:3306
    expose:
      - 3009
    volumes:
      - .data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql_database
    environment:
      PMA_HOST: mysql_database
    ports:
      - 3010:80
    expose:
      - 3010

  auth_service:
    build:
      context: auth_service/.
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - auth_service/.env
    environment:
      - PORT=3011
      - DB_HOST_PORT=mysql_database
    depends_on:
      - mysql_database
      - phpmyadmin
    ports:
      - 3011:3011


# 3009: Database Server (MySql)
# 3010: PhpMyAdmin

# 3011: Auth Service
# 3012: Product Service
# 3013: Cart Service
# 3014: Order Service
# 3015: Payment Service