version: "3"
services:
  mysql_database:
    image: mysql
    container_name: mysql_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3009:3306
    expose:
      - 3306
    volumes:
      - .data:/var/lib/mysql

  phpmyadmin_v2:
    image: phpmyadmin
    container_name: phpmyadmin_v2
    restart: unless-stopped
    depends_on:
      - mysql_database
    environment:
      PMA_HOST: mysql_database
    ports:
      - 3010:80
    expose:
      - 80

  auth_service:
    build: auth_service/.
      # context: auth_service/.
      # dockerfile: Dockerfile
    restart: always
    env_file:
      - auth_service/.env
    environment:
      - PORT=4200
      - DB_HOST_PORT=mysql_database
    depends_on:
      - mysql_database
      - phpmyadmin_v2
    ports:
      - '4200:4200'
    expose:
      - '4200'


# 3009: Database Server (MySql)
# 3010: phpmyadmin_v2

# 30011: Auth Service
# 3012: Product Service
# 3013: Cart Service
# 3014: Order Service
# 3015: Payment Service