version: "3"
services:
  mysql-database:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: catering
      # MYSQL_USER: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - .data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql-database
    environment:
      PMA_HOST: mysql-database
    ports:
      - 8080:80
    expose:
      - 8080

  auth_service:
    build:
      context: auth_service/.
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - auth_service/.env
    environment:
      - PORT=3000
      - DB_HOST=mysql-database
    depends_on:
      - mysql-database
      - phpmyadmin
    ports:
      - 3000:3000