basePath: /api/v1
definitions:
  dtos.CreateProductRequest:
    properties:
      category_id:
        description: 'required: true'
        type: integer
      condition:
        description: 'required: true'
        type: string
      description:
        description: 'required: true'
        type: string
      name:
        description: 'required: true'
        type: string
      price:
        description: 'required: true'
        type: number
      selling_by:
        description: 'required: true'
        type: integer
      thumbnail:
        description: 'required: false'
        type: string
    required:
    - category_id
    - condition
    - description
    - name
    - price
    - selling_by
    type: object
info:
  contact: {}
  description: API Documentation
  title: Product Service API Doc
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: create new product
      parameters:
      - description: Create Product Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: create new product
      tags:
      - Products
swagger: "2.0"
